package org.example.vicky.examples

import org.example.vicky.script.ClassAutoRegistry
import java.io.File

/**
 * 手动运行：生成 config/scripts/types/vicky.d.ts
 * 给 IDEA / VS Code 提供 Vicky 脚本的 TypeScript 类型补全。
 *
 * 运行方式：在 IDE 中右键 Run，或：
 *   ./gradlew :run -PmainClass=org.example.vicky.examples.GenerateTypesMainKt
 */
fun main() {
    ClassAutoRegistry.init()
    val meta = ClassAutoRegistry.classMetadata()

    val sb = StringBuilder()

    // ─── 文件头 ───
    sb.appendLine("// ═══════════════════════════════════════════════════════════════")
    sb.appendLine("// Vicky Script Type Declarations")
    sb.appendLine("// Auto-generated by GenerateTypesMain — do NOT edit manually.")
    sb.appendLine("// Re-run the generator after adding/removing injected classes.")
    sb.appendLine("// ═══════════════════════════════════════════════════════════════")
    sb.appendLine()

    // ─── 脚本返回值 ───
    sb.appendLine("""interface ScriptResult {
    /** 回传给 Agent 的内容（必填） */
    toAgent: string;
    /** 推送给用户的回复（可选） */
    userReply?: string;
    /** 是否结束本轮推理（可选） */
    endTurn?: boolean;
}
""")

    // ─── ctx 上下文对象 ───
    sb.appendLine("""/** execute(ctx, args) 中的 ctx 对象 */
interface ScriptCtx {
    /** 调用者用户 ID */
    readonly userId: string;
    /** 会话 ID */
    readonly conversationId: string;
    /** 群组 ID（私聊时为空） */
    readonly groupId: string;

    /** 发送群消息 */
    sendGroupMessage(groupId: string | number, text: string): string;
    /** 发送私聊消息 */
    sendMessage(targetId: string | number, text: string): string;
    /** 创建定时器，返回 timer 对象 */
    setTimer(intervalMs: number, callback: () => void): ScriptTimer;
}

interface ScriptTimer {
    /** 取消定时器 */
    cancel(): string;
    /** 定时间隔（毫秒） */
    readonly interval: number;
}
""")

    // ─── 协程 ───
    sb.appendLine("""interface CoroutineScope {
    /** 非阻塞延迟 */
    delay(ms: number): string;
    /** 嵌套启动子协程 */
    launch(fn: (scope: CoroutineScope) => void): string;
}

interface CoroutineAPI {
    /** 启动后台协程 */
    launch(fn: (scope: CoroutineScope) => void): string;
}

/** 全局协程对象 */
declare const coroutine: CoroutineAPI;
""")

    // ─── 脚本全局变量 ───
    sb.appendLine("""// ─── 脚本全局变量（可选导出） ─────────────────────────────────

/** 工具名称（不导出则用文件名） */
declare var name: string | undefined;

/** 工具描述 */
declare var description: string | undefined;

/** JSON Schema 参数定义 */
declare var parameters: object | undefined;

/** 工具执行函数 */
declare function execute(ctx: ScriptCtx, args: Record<string, any>): ScriptResult | Promise<ScriptResult>;

/** 脚本加载时调用 */
declare function onLoad(): void;

/** 脚本卸载时调用 */
declare function onUnload(): void;
""")

    // ─── Rhino 内置全局函数 ───
    sb.appendLine("""// ─── Rhino 内置全局函数 ──────────────────────────────────────

/** 打印到标准输出（Rhino 内置） */
declare function println(...args: any[]): void;

/** extend(BaseClass, impl, ...ctorArgs) — 动态生成 Java 抽象类/接口的子类实例 */
declare function extend<T = any>(baseClass: any, impl: Record<string, (...args: any[]) => any>, ...ctorArgs: any[]): T;

""")

    // ─── Java.type() 兜底 ───
    sb.appendLine("""// ─── Java.type() 兜底访问 ────────────────────────────────────

interface JavaAPI {
    /** 通过全限定名获取 Java 类代理 */
    type(fqn: string): any;
}

declare const Java: JavaAPI;
""")

    // ─── 按 Java → TS 类型映射 ───
    val javaToTs = mapOf(
        "String" to "string",
        "int" to "number",
        "Integer" to "number",
        "long" to "number",
        "Long" to "number",
        "float" to "number",
        "Float" to "number",
        "double" to "number",
        "Double" to "number",
        "short" to "number",
        "Short" to "number",
        "byte" to "number",
        "Byte" to "number",
        "boolean" to "boolean",
        "Boolean" to "boolean",
        "void" to "void",
        "Void" to "void",
        "Object" to "any",
        "JsonObject" to "Record<string, any>",
        "JsonElement" to "any",
        "JsonPrimitive" to "any",
    )

    fun mapType(javaType: String): String {
        // 数组
        if (javaType.endsWith("[]")) return mapType(javaType.removeSuffix("[]")) + "[]"
        // 泛型容器
        if (javaType == "List" || javaType == "Collection" || javaType == "Set" ||
            javaType == "ArrayList" || javaType == "HashSet") return "any[]"
        if (javaType == "Map" || javaType == "HashMap" || javaType == "ConcurrentHashMap")
            return "Record<string, any>"
        // 基础映射
        return javaToTs[javaType] ?: javaType
    }

    fun mapParams(params: List<org.example.vicky.script.ParamInfo>): String {
        if (params.isEmpty()) return ""
        return params.joinToString(", ") { p ->
            val tsType = mapType(p.type)
            "${p.name}: $tsType"
        }
    }

    // ─── 生成注入类声明 ───
    sb.appendLine("// ─── Auto-injected Classes ───────────────────────────────────")
    sb.appendLine("// 以下类在脚本中直接使用类名，无需 import。")
    sb.appendLine("// Kotlin object 单例 → 直接作为实例使用")
    sb.appendLine("// 普通类 → new ClassName(...) 创建实例")
    sb.appendLine()

    // 已知 object 单例列表（运行时直接注入实例）
    val objectSingletons = mutableSetOf<String>()

    for ((name, cls) in meta.entries.sortedBy { it.key }) {
        val indent = ""

        // 注释
        sb.appendLine("${indent}/** `${cls.fullClassName}` */")

        if (cls.isObject) {
            objectSingletons.add(name)
            // Kotlin object → 声明为 const 实例
            sb.appendLine("${indent}declare const $name: {")

            // 字段（只输出 static 或 object 的实例字段）
            for (f in cls.fields.filter { !it.isStatic }) {
                sb.appendLine("${indent}    ${f.name}: ${mapType(f.type)};")
            }

            // 方法
            if (cls.methods.isNotEmpty()) {
                for (m in cls.methods) {
                    val params = mapParams(m.params)
                    val ret = mapType(m.returnType)
                    sb.appendLine("${indent}    ${m.name}($params): $ret;")
                }
            }

            sb.appendLine("${indent}};")
        } else if (cls.isEnum) {
            // 枚举
            sb.appendLine("${indent}declare const $name: {")
            // 枚举值作为字段（运行时注入了枚举常量）
            for (f in cls.fields.filter { it.isStatic }) {
                sb.appendLine("${indent}    ${f.name}: $name;")
            }
            sb.appendLine("${indent}};")
        } else {
            // 普通类
            sb.appendLine("${indent}interface ${name}Interface {")
            for (f in cls.fields.filter { !it.isStatic }) {
                sb.appendLine("${indent}    ${f.name}: ${mapType(f.type)};")
            }
            for (m in cls.methods) {
                val params = mapParams(m.params)
                val ret = mapType(m.returnType)
                sb.appendLine("${indent}    ${m.name}($params): $ret;")
            }
            // Kotlin interface 属性编译为抽象 getter，cls.fields 为空；将 getXxx() 转为属性声明
            val existingFieldNames = cls.fields.map { it.name }.toSet()
            for (m in cls.methods.filter { it.params.isEmpty() && it.name.startsWith("get") && it.name.length > 3 && it.returnType != "void" }) {
                val propName = m.name.removePrefix("get").replaceFirstChar { it.lowercase() }
                if (propName !in existingFieldNames && propName != "class") {
                    sb.appendLine("${indent}    readonly $propName: ${mapType(m.returnType)};")
                }
            }
            sb.appendLine("${indent}}")
            sb.appendLine()
            // 接口合并：让 Name 同时作为类型和构造函数
            sb.appendLine("${indent}interface $name extends ${name}Interface {}")
            sb.appendLine("${indent}declare class $name {")
            // 静态字段（companion object @JvmStatic 成员等）
            for (f in cls.fields.filter { it.isStatic }) {
                sb.appendLine("${indent}    static readonly ${f.name}: ${mapType(f.type)};")
            }
            // 多参数类添加命名参数重载
            if (cls.constructors.any { it.params.size > 3 }) {
                sb.appendLine("${indent}    constructor(config: Record<string, any>);")
            }
            sb.appendLine("${indent}    constructor(...args: any[]);")
            sb.appendLine("${indent}}")
        }

        sb.appendLine()
    }

    // 写入文件
    val outDir = File("config/scripts/types")
    outDir.mkdirs()
    val outFile = File(outDir, "vicky.d.ts")
    outFile.writeText(sb.toString(), Charsets.UTF_8)

    println("Generated: ${outFile.absolutePath}")
    println("Classes: ${meta.size}")
    println("  Objects (singletons): ${objectSingletons.size}")
    println("  Classes/Enums: ${meta.size - objectSingletons.size}")
}
